import * as Joi from 'joi';

export const envValidationSchema = Joi.object({
  NODE_ENV: Joi.string().valid('development', 'test', 'production').default('development'),
  PORT: Joi.number().default(3000),
  API_PREFIX: Joi.string().default('api'),
  DATABASE_URL: Joi.string().required(),
  JWT_ACCESS_SECRET: Joi.string().min(16).required(),
  JWT_REFRESH_SECRET: Joi.string().min(16).required(),
  JWT_ACCESS_EXPIRES_IN: Joi.string().default('15m'),
  JWT_REFRESH_EXPIRES_IN: Joi.string().default('30d'),
  FIREBASE_PROJECT_ID: Joi.string().allow('', null),
  FIREBASE_CLIENT_EMAIL: Joi.string().allow('', null),
  FIREBASE_PRIVATE_KEY: Joi.string().allow('', null),
  REDIS_HOST: Joi.string().default('localhost'),
  REDIS_PORT: Joi.number().default(6379),
  REDIS_PASSWORD: Joi.string().allow('', null),
  S3_REGION: Joi.string().required(),
  S3_BUCKET: Joi.string().required(),
  S3_ACCESS_KEY_ID: Joi.string().allow('', null),
  S3_SECRET_ACCESS_KEY: Joi.string().allow('', null),
  S3_ENDPOINT: Joi.string().allow('', null),
  RAZORPAY_KEY_ID: Joi.string().allow('', null),
  RAZORPAY_KEY_SECRET: Joi.string().allow('', null),
  RAZORPAY_WEBHOOK_SECRET: Joi.string().allow('', null),
  FCM_SERVER_KEY: Joi.string().allow('', null),
  TWILIO_ACCOUNT_SID: Joi.string().allow('', null),
  TWILIO_AUTH_TOKEN: Joi.string().allow('', null),
  TWILIO_FROM_PHONE: Joi.string().allow('', null),
  OTP_EXPIRES_IN_MINUTES: Joi.number().default(5),
  OTP_MAX_ATTEMPTS: Joi.number().default(5),
  ADMIN_PANEL_ORIGIN: Joi.string().required(),
  VENDOR_PANEL_ORIGIN: Joi.string().required(),
  CORS_ORIGINS: Joi.string().allow('', null),
  SUPER_ADMIN_EMAIL: Joi.string().email().optional(),
  SUPER_ADMIN_PASSWORD: Joi.string().optional(),
});
