export enum DocumentVisibilityEnum {
  PRIVATE = 'PRIVATE',
  PET_OWNER_ONLY = 'PET_OWNER_ONLY',
  GUARDIAN_ALLOWED = 'GUARDIAN_ALLOWED',
  PUBLIC_SHARE = 'PUBLIC_SHARE',
  ADMIN_ONLY = 'ADMIN_ONLY',
}
