export enum DocumentTypeEnum {
  MEDICAL_REPORT = 'MEDICAL_REPORT',
  VACCINATION_CERTIFICATE = 'VACCINATION_CERTIFICATE',
  PASSPORT_PDF = 'PASSPORT_PDF',
  VENDOR_KYC = 'VENDOR_KYC',
  PRODUCT_IMAGE = 'PRODUCT_IMAGE',
  OTHER = 'OTHER',
}
